//! The C ABI the browser library calls.
//!
//! Hand-written rather than generated by `wasm-bindgen`, for one reason: R3.3
//! sets a size budget, and logshed's whole current client is 32 KB. A binding
//! generator brings a JS shim, a descriptor section and a lot of glue for a
//! surface that is eight functions wide and passes nothing but integers and
//! byte ranges. `web/build.sh` measures what actually ships against the
//! budget, so this is a decision with a number under it rather than a taste.
//!
//! ## Two ways in
//!
//! `supdb_open_mem` opens over bytes already copied into this module's linear
//! memory: the simplest thing, and what a test or a small index wants.
//!
//! `supdb_open_host` opens over a byte source the *host* owns, reached through
//! one imported synchronous function. That import is where R2.2(a) lands: JS
//! downloads the object into the Origin Private File System once,
//! asynchronously, and then answers `supdb_host_read` from a
//! `FileSystemSyncAccessHandle`, which is a synchronous random read. Nothing
//! on the Rust side is async, so `flatindex`'s borrow survives -- which is the
//! whole reason the option was chosen.
//!
//! ## Offsets are 32-bit here
//!
//! The host ABI takes a `u32` offset, so an object must be under 4 GiB. The
//! download budget this library is designed around is 32 MB (`w1-daysize`,
//! W1.2), so the limit is two orders of magnitude clear of anything logshed
//! will hand it, and keeping it out of BigInt keeps the JS glue plain. An
//! object at or over the limit is refused at open rather than wrapped.

use crate::blob::Blob;
use crate::bytes::{short, Bytes, VecBytes};
use std::cell::RefCell;
use std::io::Result;

/// The largest object this ABI addresses.
const MAX_OBJECT: u64 = u32::MAX as u64;

extern "C" {
    /// Total bytes of the host's object.
    fn supdb_host_len() -> u32;
    /// Read `len` bytes at `off` into `ptr`. Zero on success, anything else
    /// on failure.
    fn supdb_host_read(off: u32, ptr: *mut u8, len: u32) -> i32;
}

/// A byte source the host answers synchronously.
///
/// One call per read, and reads are whole sections at open plus one block per
/// lookup -- not one per value -- so the crossing count is bounded by the
/// structure rather than by the data.
pub struct HostBytes {
    len: u64,
}

impl HostBytes {
    fn new() -> HostBytes {
        HostBytes {
            len: unsafe { supdb_host_len() } as u64,
        }
    }
}

impl Bytes for HostBytes {
    fn len(&self) -> u64 {
        self.len
    }
    fn read_at(&self, off: u64, dst: &mut [u8]) -> Result<()> {
        let end = off
            .checked_add(dst.len() as u64)
            .ok_or_else(|| short(off, dst.len(), self.len))?;
        if end > self.len {
            return Err(short(off, dst.len(), self.len));
        }
        let rc = unsafe { supdb_host_read(off as u32, dst.as_mut_ptr(), dst.len() as u32) };
        if rc != 0 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!("the host refused a read of {} bytes at {off}", dst.len()),
            ));
        }
        Ok(())
    }
    // No `slice_at`: the host's bytes are not in this module's memory, so
    // there is nothing to lend. Sections are copied once at open instead.
    // No `advise_random` either -- R2.4, a no-op where there is no mapping.
}

enum AnyBlob {
    Mem(Blob<VecBytes>),
    Host(Blob<HostBytes>),
}

/// Everything the module holds between calls.
///
/// One thread, because wasm32-unknown-unknown is one thread and a Web Worker
/// is one thread. A `RefCell` here is a real check rather than a formality:
/// a host callback that re-entered would be caught instead of corrupting.
struct State {
    blobs: Vec<Option<AnyBlob>>,
    out: Vec<u8>,
    err: String,
}

thread_local! {
    static STATE: RefCell<State> = RefCell::new(State {
        blobs: Vec::new(),
        out: Vec::new(),
        err: String::new(),
    });
}

fn fail<T>(msg: impl Into<String>, sentinel: T) -> T {
    STATE.with(|s| s.borrow_mut().err = msg.into());
    sentinel
}

/// Run `f` against the blob at `h`, reporting an error rather than trapping.
fn with_blob<T>(h: u32, sentinel: T, f: impl FnOnce(&AnyBlob, &mut Vec<u8>) -> Result<T>) -> T {
    let taken = STATE.with(|s| {
        let mut st = s.borrow_mut();
        st.err.clear();
        match st.blobs.get_mut(h as usize) {
            Some(slot) => slot.take(),
            None => None,
        }
    });
    let Some(blob) = taken else {
        return fail(format!("no open reader with handle {h}"), sentinel);
    };
    // The blob is out of the table for the duration, so a host callback that
    // re-enters cannot alias it. Put back before returning, always.
    let mut out = STATE.with(|s| std::mem::take(&mut s.borrow_mut().out));
    out.clear();
    let r = f(&blob, &mut out);
    STATE.with(|s| {
        let mut st = s.borrow_mut();
        st.out = out;
        st.blobs[h as usize] = Some(blob);
    });
    match r {
        Ok(v) => v,
        Err(e) => fail(e.to_string(), sentinel),
    }
}

fn put(state_blob: AnyBlob) -> u32 {
    STATE.with(|s| {
        let mut st = s.borrow_mut();
        st.err.clear();
        st.blobs.push(Some(state_blob));
        (st.blobs.len() - 1) as u32
    })
}

// ------------------------------------------------------------------ memory --

/// Allocate `len` bytes in this module's memory. The host writes an object
/// into it and hands the pointer to `supdb_open_mem`.
///
/// # Safety
/// The returned pointer is only valid until `supdb_free` is called with the
/// same pointer and length.
#[no_mangle]
pub extern "C" fn supdb_alloc(len: u32) -> *mut u8 {
    // `vec![0u8; n]` allocates exactly `n`, where `with_capacity` may
    // allocate more. `supdb_free` and `supdb_open_mem` both reconstruct the
    // `Vec` with capacity `len`, and handing the allocator back a capacity it
    // did not give out is undefined behaviour rather than a leak.
    let mut v = vec![0u8; len as usize];
    let p = v.as_mut_ptr();
    std::mem::forget(v);
    p
}

/// Release memory from `supdb_alloc`.
///
/// # Safety
/// `ptr` and `len` must be exactly what `supdb_alloc` returned and was given.
#[no_mangle]
pub unsafe extern "C" fn supdb_free(ptr: *mut u8, len: u32) {
    if !ptr.is_null() {
        drop(Vec::from_raw_parts(ptr, 0, len as usize));
    }
}

// ------------------------------------------------------------------ errors --

#[no_mangle]
pub extern "C" fn supdb_error_ptr() -> *const u8 {
    STATE.with(|s| s.borrow().err.as_ptr())
}

#[no_mangle]
pub extern "C" fn supdb_error_len() -> u32 {
    STATE.with(|s| s.borrow().err.len() as u32)
}

/// Pointer to the framed result of the last call that produced one.
#[no_mangle]
pub extern "C" fn supdb_out_ptr() -> *const u8 {
    STATE.with(|s| s.borrow().out.as_ptr())
}

// ------------------------------------------------------------------ open --

/// Open over bytes in this module's memory. Takes ownership of them.
///
/// Returns a handle, or `u32::MAX` on failure -- read `supdb_error_*` then.
///
/// # Safety
/// `ptr` must point at `len` initialised bytes from `supdb_alloc`.
#[no_mangle]
pub unsafe extern "C" fn supdb_open_mem(ptr: *mut u8, len: u32) -> u32 {
    let v = Vec::from_raw_parts(ptr, len as usize, len as usize);
    match Blob::open(VecBytes(v)) {
        Ok(b) => put(AnyBlob::Mem(b)),
        Err(e) => fail(e.to_string(), u32::MAX),
    }
}

/// Open over the host's byte source, reached through `supdb_host_read`.
///
/// Returns a handle, or `u32::MAX` on failure.
#[no_mangle]
pub extern "C" fn supdb_open_host() -> u32 {
    let src = HostBytes::new();
    if src.len() >= MAX_OBJECT {
        return fail(
            format!(
                "this ABI addresses objects below {MAX_OBJECT} bytes and the host offered {}",
                src.len()
            ),
            u32::MAX,
        );
    }
    match Blob::open(src) {
        Ok(b) => put(AnyBlob::Host(b)),
        Err(e) => fail(e.to_string(), u32::MAX),
    }
}

#[no_mangle]
pub extern "C" fn supdb_close(h: u32) {
    STATE.with(|s| {
        let mut st = s.borrow_mut();
        if let Some(slot) = st.blobs.get_mut(h as usize) {
            *slot = None;
        }
    });
}

// ------------------------------------------------------------------ reads --

macro_rules! on {
    ($b:expr, $m:ident $(, $a:expr)*) => {
        match $b {
            AnyBlob::Mem(x) => x.$m($($a),*),
            AnyBlob::Host(x) => x.$m($($a),*),
        }
    };
}

/// Number of distinct keys. R4.5.
#[no_mangle]
pub extern "C" fn supdb_keys(h: u32) -> u32 {
    with_blob(h, u32::MAX, |b, _| Ok(on!(b, keys) as u32))
}

/// Bytes of key index. R4.5.
#[no_mangle]
pub extern "C" fn supdb_index_bytes(h: u32) -> u32 {
    with_blob(h, u32::MAX, |b, _| Ok(on!(b, index_bytes) as u32))
}

/// Checkpoint generation this reader opened.
#[no_mangle]
pub extern "C" fn supdb_generation(h: u32) -> u32 {
    with_blob(h, u32::MAX, |b, _| Ok(on!(b, version).0 as u32))
}

/// Values under a key, without decoding them. R4.3.
///
/// Returns the count, or `u64::MAX` on error. Note what it does *not* do:
/// nothing crosses this boundary per value, which is most of what the count
/// is for on this side of it.
///
/// # Safety
/// `kptr` must point at `klen` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn supdb_count(h: u32, kptr: *const u8, klen: u32) -> u64 {
    let key = std::slice::from_raw_parts(kptr, klen as usize);
    with_blob(h, u64::MAX, |b, _| on!(b, count, key))
}

/// Stored bytes under a key -- payload plus one varint length prefix per
/// value. O(extents): no block is touched, not even to fault a page in.
///
/// # Safety
/// `kptr` must point at `klen` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn supdb_stored_bytes(h: u32, kptr: *const u8, klen: u32) -> u64 {
    let key = std::slice::from_raw_parts(kptr, klen as usize);
    with_blob(h, u64::MAX, |b, _| Ok(on!(b, stored_bytes, key)))
}

/// The count in O(extents), for a posting list of fixed-width values.
///
/// `u64::MAX` when the stored bytes are not a multiple of the stride, which
/// is what a key whose values are not all `width` bytes looks like -- the
/// caller should fall back to `supdb_count` rather than treat it as zero.
/// logshed's postings are four-byte line ordinals, so this is the call it
/// wants for a breakdown panel.
///
/// # Safety
/// `kptr` must point at `klen` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn supdb_count_fixed(h: u32, kptr: *const u8, klen: u32, width: u32) -> u64 {
    let key = std::slice::from_raw_parts(kptr, klen as usize);
    with_blob(h, u64::MAX, |b, _| {
        Ok(on!(b, count_fixed, key, width).unwrap_or(u64::MAX))
    })
}

/// Every value of a key, framed into the out buffer. R4.2.
///
/// Layout: `u32 n`, then `n` records of `u32 len` followed by `len` bytes.
/// Returns the total framed length, or `u32::MAX` on error. The bytes live at
/// `supdb_out_ptr()` until the next call.
///
/// # Safety
/// `kptr` must point at `klen` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn supdb_lookup(h: u32, kptr: *const u8, klen: u32) -> u32 {
    let key = std::slice::from_raw_parts(kptr, klen as usize);
    with_blob(h, u32::MAX, |b, out| {
        out.extend_from_slice(&0u32.to_le_bytes());
        let n = on!(b, read_all, key, |v: &[u8]| {
            out.extend_from_slice(&(v.len() as u32).to_le_bytes());
            out.extend_from_slice(v);
        })?;
        out[0..4].copy_from_slice(&(n as u32).to_le_bytes());
        Ok(out.len() as u32)
    })
}

/// Keys in order from `from`, each with its value count. R4.4.
///
/// Layout: `u32 n`, then `n` records of `u32 klen`, `u32 count_lo`,
/// `u32 count_hi`, then `klen` key bytes. Returns the framed length, or
/// `u32::MAX` on error.
///
/// # Safety
/// `fptr` must point at `flen` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn supdb_scan_counts(
    h: u32,
    fptr: *const u8,
    flen: u32,
    limit: u32,
) -> u32 {
    let from = std::slice::from_raw_parts(fptr, flen as usize);
    with_blob(h, u32::MAX, |b, out| {
        out.extend_from_slice(&0u32.to_le_bytes());
        let n = on!(b, scan_counts, from, limit as usize, |k: &[u8], c: u64| {
            out.extend_from_slice(&(k.len() as u32).to_le_bytes());
            out.extend_from_slice(&(c as u32).to_le_bytes());
            out.extend_from_slice(&((c >> 32) as u32).to_le_bytes());
            out.extend_from_slice(k);
            true
        })?;
        out[0..4].copy_from_slice(&(n as u32).to_le_bytes());
        Ok(out.len() as u32)
    })
}
